// frontend/src/components/layout/AppLayout.vue
<template>
  <div class="min-h-screen bg-gray-50 dark:bg-dark-950">
    <!-- Background Decoration -->
    <div class="pointer-events-none fixed inset-0 bg-mesh-gradient"></div>

    <!-- Sidebar -->
    <AppSidebar />

    <!-- Main Content Area -->
    <div
      class="relative min-h-screen transition-all duration-300"
      :class="[sidebarCollapsed ? 'lg:ml-[72px]' : 'lg:ml-64']"
    >
      <!-- Header -->
      <AppHeader />

      <!-- Main Content -->
      <main class="p-4 md:p-6 lg:p-8">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import '@/styles/onboarding.css'
import { computed, onMounted } from 'vue'
import { useAppStore } from '@/stores'
import { useAuthStore } from '@/stores/auth'
import { useOnboardingTour } from '@/composables/useOnboardingTour'
import { useOnboardingStore } from '@/stores/onboarding'
import AppSidebar from './AppSidebar.vue'
import AppHeader from './AppHeader.vue'

const appStore = useAppStore()
const authStore = useAuthStore()
const sidebarCollapsed = computed(() => appStore.sidebarCollapsed)
const isAdmin = computed(() => authStore.user?.role === 'admin')

const { replayTour, startTour, hasSeen } = useOnboardingTour({
  storageKey: isAdmin.value ? 'admin_guide' : 'user_guide',
  autoStart: false
})

const onboardingStore = useOnboardingStore()

onMounted(async () => {
  onboardingStore.setReplayCallback(replayTour)

  // Fetch latest public settings with force refresh (ensures onboarding_enabled reflects current DB value,
  // bypassing any stale cache from before the user logged in)
  const settings = await appStore.fetchPublicSettings(true)
  if (settings?.onboarding_enabled && !hasSeen()) {
    await startTour()
  }
})

defineExpose({ replayTour })
</script>

// frontend-react/src/components/layout/AppLayout.tsx
/**
 * Main Application Layout
 * Wraps authenticated pages with sidebar + header.
 * Mirrors the Vue AppLayout.vue implementation.
 */

import { Outlet } from '@tanstack/react-router'
import { useAppStore } from '@/stores/app'
import { useOnboardingTour } from '@/hooks/useOnboardingTour'
import AppSidebar from './AppSidebar'
import AppHeader from './AppHeader'

export default function AppLayout() {
  const sidebarCollapsed = useAppStore((s) => s.sidebarCollapsed)
  useOnboardingTour({ autoStart: true })

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-dark-950">
      {/* Background Decoration */}
      <div className="pointer-events-none fixed inset-0 bg-mesh-gradient" />

      {/* Sidebar */}
      <AppSidebar />

      {/* Main Content Area */}
      <div
        className={`relative min-h-screen transition-all duration-300 ${
          sidebarCollapsed ? 'lg:ml-[72px]' : 'lg:ml-64'
        }`}
      >
        {/* Header */}
        <AppHeader />

        {/* Main Content */}
        <main className="p-4 md:p-6 lg:p-8">
          <Outlet />
        </main>
      </div>
    </div>
  )
}
